apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmu-fe-strategic
  labels:
    app: rmu-fe-strategic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmu-fe-strategic
  template:
    metadata:
      labels:
        app: rmu-fe-strategic
    spec:
      containers:
      - name: rmu-fe-strategic
        image: labcabrera/rmu-fe-strategic:latest
        ports:
        - containerPort: 8080
        env:
        - name: RMU_FE_STRATEGIC_PUBLIC_PATH
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_FE_STRATEGIC_PUBLIC_PATH
